services:
  clubit_postgres:
    container_name: clubit_postgres
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: clubit_db
    ports:
      - '5432:5432'
    volumes:
      - clubit_postgres_data:/var/lib/postgresql/data
    networks:
      - clubit_network
  clubit-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clubit_back
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      # OJO: Aquí 'host' debe ser el nombre del servicio de la BD docker
      DATABASE_URL: "postgresql://dev:devpass@clubit_postgres:5432/clubit_db?schema=public"
    depends_on:
      - clubit_postgres
    networks:
      - clubit_network
volumes:
  clubit_postgres_data:
networks:
  clubit_network:
    name: clubit_network
    driver: bridge